#!/bin/bash

export OMP_SCHEDULE="static"
	
	echo "secuencial"
	echo "100 elementos"
	./pmm-secuencial 100
	echo "1500 elementos"
	./pmm-secuencial 1500

	export OMP_NUM_THREADS=2
	echo "2 cores"
	echo "100 elementos"
	./pmm-OpenMP 100
	echo "1500 elementos"
	./pmm-OpenMP 1500
