#!/bin/bash

export OMP_SCHEDULE="static"

	echo "secuencial"
	echo "100 elementos"
	./pmm-secuencial 100
	echo "1500 elementos"
	./pmm-secuencial 1500

	export OMP_NUM_THREADS=2
	echo "2 cores"
	echo "100 elementos"
	./pmm-OpenMP 100
	echo "1500 elementos"
	./pmm-OpenMP 1500
	
	export OMP_NUM_THREADS=4
	echo "4 cores"
	echo "100 elementos"
	./pmm-OpenMP 100
	echo "1500 elementos"
	./pmm-OpenMP 1500
	
	export OMP_NUM_THREADS=6
	echo "6 cores"
	echo "100 elementos"
	./pmm-OpenMP 100
	echo "1500 elementos"
	./pmm-OpenMP 1500

	export OMP_NUM_THREADS=8
	echo "8 cores"
	echo "100 elementos"
	./pmm-OpenMP 100
	echo "1500 elementos"
	./pmm-OpenMP 1500

	export OMP_NUM_THREADS=10
	echo "10 cores"
	echo "100 elementos"
	./pmm-OpenMP 100
	echo "1500 elementos"
	./pmm-OpenMP 1500

	export OMP_NUM_THREADS=12
	echo "12 cores"
	echo "100 elementos"
	./pmm-OpenMP 100
	echo "1500 elementos"
	./pmm-OpenMP 1500
