#!/bin/bash
echo 'a 1k'
./pmv-OpenMP-a 1000
echo 'b 1k'
./pmv-OpenMP-b 1000
echo 'reduction 1k'
./pmv-OpenMP-reduction 1000
echo 'a 7.5k'
./pmv-OpenMP-a 7500
echo 'b 7.5k'
./pmv-OpenMP-b 7500
echo 'reduction 7.5k'
./pmv-OpenMP-reduction 7500
echo 'a 15k'
./pmv-OpenMP-a 15000 
echo 'b 15k'
./pmv-OpenMP-b 15000 
echo 'reduction 15k'
./pmv-OpenMP-reduction 15000 
