/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.BadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.DeathBadConsequence;
import NapakalakiGame.TreasureKind;
/**
 *
 * @author anonymous
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {
    BadConsequence bd;
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }
    public void setPendingBadConsequence(BadConsequence b){
        bd=b;
        SpecificVisibleTreasures.setText("Ningun svt");
        SpecificHiddenTreasures.setText("Ningun sht");
        nVisibleTreasures.setText("Ningun nVT");
        nHiddenTreasures.setText("Ningun nHT");
        if(bd!=null){
            if(bd instanceof SpecificBadConsequence){
                if(!((SpecificBadConsequence)bd).getSpecificVisibleTreasures().isEmpty()){
                    SpecificVisibleTreasures.setText(String.valueOf(((SpecificBadConsequence)bd).getSpecificVisibleTreasures()));
                }
                if(!((SpecificBadConsequence)bd).getSpecificHiddenTreasures().isEmpty()){
                    SpecificHiddenTreasures.setText(String.valueOf(((SpecificBadConsequence)bd).getSpecificHiddenTreasures()));
                }
            }
            if(bd instanceof NumericBadConsequence){
                nVisibleTreasures.setText(String.valueOf(((NumericBadConsequence)bd).getNVisibleTreasures()));
                nHiddenTreasures.setText(String.valueOf(((NumericBadConsequence)bd).getNHiddenTreasures()));
            }
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nVisibleTreasures = new javax.swing.JLabel();
        nHiddenTreasures = new javax.swing.JLabel();
        SpecificVisibleTreasures = new javax.swing.JLabel();
        SpecificHiddenTreasures = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("NVisibles");

        jLabel2.setText("NHidden");

        jLabel3.setText("nSpecificVisible");

        jLabel4.setText("nSpecificHidden");

        nVisibleTreasures.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nVisibleTreasures.setText(" ");

        nHiddenTreasures.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nHiddenTreasures.setText(" ");

        SpecificVisibleTreasures.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SpecificVisibleTreasures.setText(" ");

        SpecificHiddenTreasures.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SpecificHiddenTreasures.setText(" ");

        jLabel5.setText("PendingBadConsequence: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SpecificHiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(SpecificVisibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel5)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nVisibleTreasures))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nHiddenTreasures))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SpecificVisibleTreasures))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SpecificHiddenTreasures)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SpecificHiddenTreasures;
    private javax.swing.JLabel SpecificVisibleTreasures;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nHiddenTreasures;
    private javax.swing.JLabel nVisibleTreasures;
    // End of variables declaration//GEN-END:variables
}
