/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.Prize;
import javax.swing.Icon;
import javax.swing.ImageIcon;
/**
 *
 * @author anonymous
 */
public class PrizeView extends javax.swing.JPanel {
    private Prize p;
    private Object imagen;
    /**
     * Creates new form PrizeView
     */
    
    public PrizeView() {
        initComponents();
    }
    public void setPrize(Prize p2){
        p=p2;
        jLabel1.setText("Numero de tesoros: ");
        treasures.setText(String.valueOf(p.getTreasures()));
        nlevels.setText(String.valueOf(p.getLevel()));
        jLabel3.setText("Numero de niveles: ");
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nlevels = new javax.swing.JLabel();
        treasures = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 22, -1, -1));

        nlevels.setText("jLabel2");
        add(nlevels, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        treasures.setText("jLabel1");
        add(treasures, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nlevels;
    private javax.swing.JLabel treasures;
    // End of variables declaration//GEN-END:variables
}
