/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.lucene.facet.FacetsCollector;
import org.apache.lucene.facet.taxonomy.TaxonomyReader;
import org.apache.lucene.facet.taxonomy.directory.DirectoryTaxonomyReader;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexReader;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;
import practica3b.Practica3b;
/**
 *
 * @author Javi
 */
public class VistaPrincipal extends javax.swing.JFrame {
    private FacetsCollector fc;
    private IndexSearcher is;
    private TaxonomyReader tr;
    private resultados r;
    TopDocs td;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal(){
        initComponents();
        fechas_especificas.setSelected(true);
        por_relevancia.setSelected(true);
        or.setSelected(true);
        r=new resultados();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        busqueda_titulo = new javax.swing.JButton();
        busqueda_autor = new javax.swing.JButton();
        busqueda_resumen = new javax.swing.JButton();
        or = new javax.swing.JRadioButton();
        and = new javax.swing.JRadioButton();
        texto_busqueda = new javax.swing.JTextField();
        fecha1 = new javax.swing.JTextField();
        fecha2 = new javax.swing.JTextField();
        fechas_rango = new javax.swing.JRadioButton();
        fechas_especificas = new javax.swing.JRadioButton();
        por_relevancia = new javax.swing.JRadioButton();
        por_anio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        busqueda_titulo.setText("Busqueda por título");
        busqueda_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_tituloActionPerformed(evt);
            }
        });

        busqueda_autor.setText("Busqueda por autor");
        busqueda_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_autorActionPerformed(evt);
            }
        });

        busqueda_resumen.setText("Busqueda por resumen");
        busqueda_resumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_resumenActionPerformed(evt);
            }
        });

        buttonGroup1.add(or);
        or.setText("  OR");
        or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orActionPerformed(evt);
            }
        });

        buttonGroup1.add(and);
        and.setText("AND");
        and.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andActionPerformed(evt);
            }
        });

        texto_busqueda.setText("Introduce tu busqueda");
        texto_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_busquedaActionPerformed(evt);
            }
        });

        fecha1.setText("Fecha 1");

        fecha2.setText("Fecha 2");

        buttonGroup2.add(fechas_rango);
        fechas_rango.setText("Rango de fechas");

        buttonGroup2.add(fechas_especificas);
        fechas_especificas.setText("Fechas especificas");
        fechas_especificas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechas_especificasActionPerformed(evt);
            }
        });

        buttonGroup4.add(por_relevancia);
        por_relevancia.setText("Ordenar por relevancia");

        buttonGroup4.add(por_anio);
        por_anio.setText("Ordenar por año");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(texto_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechas_rango)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechas_especificas))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(busqueda_resumen)
                    .addComponent(busqueda_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busqueda_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(or)
                    .addComponent(and))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(por_relevancia)
                    .addComponent(por_anio))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(texto_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(busqueda_titulo)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(and)
                    .addComponent(por_relevancia))
                .addGap(1, 1, 1)
                .addComponent(busqueda_autor)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(or)
                            .addComponent(por_anio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(busqueda_resumen)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechas_rango)
                    .addComponent(fechas_especificas))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void setRutas(String r1, String r2) throws IOException{
        Directory dir=FSDirectory.open(Paths.get("C:\\index"));
        IndexReader reader=DirectoryReader.open(dir);
        is=new IndexSearcher(reader);
        //index2=r2;
        Directory taxoDir=FSDirectory.open(Paths.get(r2));
        tr=new DirectoryTaxonomyReader(taxoDir);
    }
    private void orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orActionPerformed
        
    }//GEN-LAST:event_orActionPerformed
    
    private void andActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_andActionPerformed

    private void texto_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_busquedaActionPerformed

    private void busqueda_resumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_resumenActionPerformed
        String b=new String();
        String tipo_busqueda="";
        String tipo_orden="";
        String tipo_year="";
        Integer n1=null, n2=null;
        if(texto_busqueda.getText()!=null){
            b=texto_busqueda.getText();
            if(fecha1.getText()!=null){
                if(Practica3b.isNumeric(fecha1.getText())) n1=Integer.parseInt(fecha1.getText());
                else n1=null;
            }
            if(fecha2.getText()!=null){
                if(Practica3b.isNumeric(fecha2.getText())) n2=Integer.parseInt(fecha2.getText());
                else n2=null;
            }      
        }
        if(fechas_rango.isSelected()) tipo_year="range";
        else tipo_year="set";
        if(and.isSelected()) tipo_busqueda="must";
        else tipo_busqueda="should";
        if(por_relevancia.isSelected()) tipo_orden="score";
        else tipo_orden="year";
        TopDocs td;
        try {
            td = Practica3b.busqueda(is, tipo_orden,tipo_busqueda, tipo_year, "", b, n1, n2);
            r.setTD_and_searcher(td, is);
            r.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busqueda_resumenActionPerformed

    private void busqueda_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_tituloActionPerformed
        String b=new String();
        String tipo_busqueda="";
        String tipo_year="";
        String tipo_orden="";
        Integer n1=null, n2=null;
        if(texto_busqueda.getText()!=null){
            b=texto_busqueda.getText();
            if(fecha1.getText()!=null){
                if(Practica3b.isNumeric(fecha1.getText())) n1=Integer.parseInt(fecha1.getText());
                else n1=null;
            }
            if(fecha2.getText()!=null){
                if(Practica3b.isNumeric(fecha2.getText())) n2=Integer.parseInt(fecha2.getText());
                else n2=null;
            }      
        }
        if(fechas_rango.isSelected()) tipo_year="range";
        else tipo_year="set";
        if(and.isSelected()) tipo_busqueda="must";
        else tipo_busqueda="should";
        if(por_relevancia.isSelected()) tipo_orden="score";
        else tipo_orden="year";
        TopDocs td;
        try {
            td = Practica3b.busqueda(is, tipo_orden,tipo_busqueda, tipo_year, b, "", n1, n2);
            //td=Practica3b.busqueda(is, "should", "range", "twitter", null, null, null);
            r.setTD_and_searcher(td, is);
            r.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_busqueda_tituloActionPerformed

    private void fechas_especificasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechas_especificasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechas_especificasActionPerformed

    private void busqueda_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_autorActionPerformed
       String b=new String();
        String tipo_busqueda="";
        String tipo_year="";
        Integer n1=null, n2=null;
        if(texto_busqueda.getText()!=null){
            b=texto_busqueda.getText();
            if(fecha1.getText()!=null){
                if(Practica3b.isNumeric(fecha1.getText())) n1=Integer.parseInt(fecha1.getText());
                else n1=null;
            }
            if(fecha2.getText()!=null){
                if(Practica3b.isNumeric(fecha2.getText())) n2=Integer.parseInt(fecha2.getText());
                else n2=null;
            }      
        }
        if(fechas_rango.isSelected()) tipo_year="range";
        else tipo_year="set";
        if(and.isSelected()) tipo_busqueda="must";
        else tipo_busqueda="should";
        TopDocs td;
        try {
            td=Practica3b.busquedaAuthor(is, tipo_busqueda, tipo_year, b, n1, n2, fc);
            r.setTD_searcher_taxoReader_facetsCollector(td, is, tr, fc);
            r.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busqueda_autorActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton and;
    private javax.swing.JButton busqueda_autor;
    private javax.swing.JButton busqueda_resumen;
    private javax.swing.JButton busqueda_titulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JTextField fecha1;
    private javax.swing.JTextField fecha2;
    private javax.swing.JRadioButton fechas_especificas;
    private javax.swing.JRadioButton fechas_rango;
    private javax.swing.JRadioButton or;
    private javax.swing.JRadioButton por_anio;
    private javax.swing.JRadioButton por_relevancia;
    private javax.swing.JTextField texto_busqueda;
    // End of variables declaration//GEN-END:variables
}
