/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.Player;
import NapakalakiGame.Treasure;
import NapakalakiGame.TreasureKind;
import java.util.ArrayList;
import javax.swing.JPanel;
import NapakalakiGame.Napakalaki;
import java.awt.Component;
import NapakalakiGame.CultistPlayer;

/**
 *
 * @author Javi
 */
public class Playerview extends javax.swing.JPanel {
    Player playerModel;
    private Object imagen;
    private Napakalaki napakalakiModel;
    /**
     * Creates new form Playerview
     */
    public Playerview() {
        initComponents();
    }
    public void TodosBotonesFalse(){
        MakeVisible.setEnabled(false);
        StealTreasure.setEnabled(false);
        DiscardAll.setEnabled(false);
        Discard.setEnabled(false);
    }
    public void DiscardsToTrue(){
        DiscardAll.setEnabled(true);
        Discard.setEnabled(true);
    }
    public void AllTrue(){
        if(playerModel.canISteal()){
            StealTreasure.setEnabled(true);
        }
        MakeVisible.setEnabled(true);
        DiscardAll.setEnabled(true);
        Discard.setEnabled(true);
    }
    public void setPlayer (Player p) {
playerModel = p;
if(playerModel instanceof CultistPlayer){
    SoyCultist.setText("Soy Cultist");
}
else{
    SoyCultist.setText(" ");
}
nCultists.setText(String.valueOf(CultistPlayer.getTotalCultistPlayers()));
pendingBadConsequenceView1.setPendingBadConsequence(playerModel.getPendingBadConsequence());
jLabel5.setText(playerModel.getName());
jLabel8.setText(String.valueOf(playerModel.getLevels()));
jLabel9.setText(String.valueOf(playerModel.getCombatLevel()));
jLabel10.setText(playerModel.getEnemy().getName());
if(playerModel.isDead()){
    jLabel13.setText("Si");
}else{
    jLabel13.setText("No");
}
if(playerModel.canISteal()){
    jLabel14.setText("Si");
}else{
    jLabel14.setText("No");
}
if(playerModel.canISteal() && playerModel.getLevels()<10){
    StealTreasure.setEnabled(true);
}

// Incluir instrucciones para actualizar su nombre, nivel, etc.

// A continuación se actualizan sus tesoros
this.fillTreasurePanel(visibleTreasures,playerModel.getVisibleTreasures());
this.fillTreasurePanel(hiddenTreasures,playerModel.getHiddenTreasures());
repaint();
revalidate();
}
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
// Se recorren los tesoros que contiene el panel,
// almacenando en un vector aquellos que están seleccionados.
// Finalmente se devuelve dicho vector.
TreasureView tv;
ArrayList<Treasure> output = new ArrayList();
for (Component c : aPanel.getComponents()) {
tv = (TreasureView) c;
if ( tv.isSelected() )
 output.add ( tv.getTreasure() );
}
return output;
}
    public void setNapakalakiModel(Napakalaki n){
        napakalakiModel=n;
        
    }
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
// Se elimina la información antigua, si la hubiera
aPanel.removeAll();
// Se recorre la lista de tesoros construyendo y añadiendo sus vistas
// al panel
for (Treasure t : aList) {
TreasureView aTreasureView = new TreasureView();
aTreasureView.setTreasure (t);
aTreasureView.setVisible (true);
aPanel.add (aTreasureView);
}
// Se fuerza la actualización visual del panel
aPanel.repaint();
aPanel.revalidate();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MakeVisible = new javax.swing.JButton();
        StealTreasure = new javax.swing.JButton();
        DiscardAll = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Discard = new javax.swing.JButton();
        pendingBadConsequenceView1 = new GUI.PendingBadConsequenceView();
        hiddenTreasures = new javax.swing.JPanel();
        visibleTreasures = new javax.swing.JPanel();
        SoyCultist = new javax.swing.JLabel();
        nCultists = new javax.swing.JLabel();
        nCultistss = new javax.swing.JLabel();
        ResultadosRobar = new javax.swing.JLabel();

        jButton3.setText("Descartar Tesoro");

        jLabel1.setText("Tesoros Visibles:");

        jLabel2.setText("Tesoros escondidos:");

        MakeVisible.setText("Hacer Visible");
        MakeVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeVisibleActionPerformed(evt);
            }
        });

        StealTreasure.setText("Robar Tesoro");
        StealTreasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StealTreasureActionPerformed(evt);
            }
        });

        DiscardAll.setText("Descartar Todos");
        DiscardAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardAllActionPerformed(evt);
            }
        });

        jLabel4.setText("Nivel:");

        jLabel5.setText("jLabel5");

        jLabel6.setText("Nivel de combate:");

        jLabel7.setText("Enemigo");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("Muerto");

        jLabel12.setText("¿Robar?");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        Discard.setText("Descartar ");
        Discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardActionPerformed(evt);
            }
        });

        hiddenTreasures.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        visibleTreasures.setPreferredSize(new java.awt.Dimension(637, 122));

        SoyCultist.setText("jLabel3");

        nCultists.setText("jLabel3");

        nCultistss.setText("NCultists: ");

        ResultadosRobar.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendingBadConsequenceView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SoyCultist, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nCultistss)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(StealTreasure))
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(MakeVisible)
                                                .addGap(28, 28, 28)
                                                .addComponent(Discard, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)))
                                    .addComponent(nCultists)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(DiscardAll)))))
                        .addContainerGap(117, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(hiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ResultadosRobar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoyCultist)
                    .addComponent(nCultists)
                    .addComponent(nCultistss))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pendingBadConsequenceView1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(ResultadosRobar)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakeVisible)
                    .addComponent(StealTreasure)
                    .addComponent(DiscardAll)
                    .addComponent(Discard))
                .addContainerGap())
        );

        jLabel4.setText("Nivel");
    }// </editor-fold>//GEN-END:initComponents

    public void SetStealTreasureEmpty(){
        ResultadosRobar.setText(" ");
        setPlayer(playerModel);
    }
    private void StealTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StealTreasureActionPerformed
        Treasure t=napakalakiModel.getCurrentPlayer().stealTreasure();
        if(t==null) ResultadosRobar.setText("No has podido robar");
        else ResultadosRobar.setText("Has conseguido robar");
        setPlayer(playerModel);
    }//GEN-LAST:event_StealTreasureActionPerformed

    private void MakeVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeVisibleActionPerformed
        ArrayList<Treasure>selHidden=getSelectedTreasures(hiddenTreasures);
        napakalakiModel.makeTreasuresVisible(selHidden);
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_MakeVisibleActionPerformed

    private void DiscardAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardAllActionPerformed
        napakalakiModel.getCurrentPlayer().discardAllTreasures();
        setPlayer(playerModel);
    }//GEN-LAST:event_DiscardAllActionPerformed

    private void DiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardActionPerformed
        ArrayList<Treasure>selHidden=getSelectedTreasures(hiddenTreasures);
        ArrayList<Treasure>selVisible=getSelectedTreasures(visibleTreasures);
        for(Treasure t: selHidden){
            napakalakiModel.getCurrentPlayer().discardHiddenTreasure(t);
        }
        for(Treasure t: selVisible){
            napakalakiModel.getCurrentPlayer().discardVisibleTreasure(t);
        }
        setPlayer(playerModel);
    }//GEN-LAST:event_DiscardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Discard;
    private javax.swing.JButton DiscardAll;
    private javax.swing.JButton MakeVisible;
    private javax.swing.JLabel ResultadosRobar;
    private javax.swing.JLabel SoyCultist;
    private javax.swing.JButton StealTreasure;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nCultists;
    private javax.swing.JLabel nCultistss;
    private GUI.PendingBadConsequenceView pendingBadConsequenceView1;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
